import { batikMen, batikWomen } from "@/assets/images";
import Batik1 from "@/assets/img/batik/batik1.jpg";
import Batik2 from "@/assets/img/batik/batik2.jpg";
import Batik3 from "@/assets/img/batik/batik3.jpg";
import Batik4 from "@/assets/img/batik/batik4.png";

// TODO: Mengubah tiap item batik sesuai dengan warna yang sesuai

export const products = [
  {
    id: 1,
    name: "Batik Tulis Modern",
    image: [
      { src: batikMen.Batik1Biru, color: "Biru" },
      { src: batikMen.Batik1Merah, color: "Merah" },
      { src: batikMen.Batik1Hijau, color: "Hijau" },
      { src: batikMen.Batik1Kuning, color: "Kuning" },
      { src: batikMen.Batik1Jingga, color: "Jingga" },
      { src: batikMen.Batik1Salem, color: "Salem" },
    ],
    price: 150000,
    rating: 4.5,
    gender: "Pria",
    sold: 120,
  },
  {
    id: 2,
    name: "Batik Cap Tradisional",
    image: [
      { src: batikWomen.Batik3Salem, color: "Salem" },
      { src: batikWomen.Batik3Biru, color: "Biru" },
      { src: batikWomen.Batik3Merah, color: "Merah" },
      { src: batikWomen.Batik3Hijau, color: "Hijau" },
      { src: batikWomen.Batik3Kuning, color: "Kuning" },
      { src: batikWomen.Batik3Jingga, color: "Jingga" },
    ],
    price: 130000,
    rating: 4,
    gender: "Wanita",
    sold: 85,
  },
  {
    id: 3,
    name: "Batik Pekalongan",
    image: [
      { src: batikMen.Batik2Jingga, color: "Jingga" },
      { src: batikMen.Batik2Merah, color: "Merah" },
      { src: batikMen.Batik2Biru, color: "Biru" },
      // { src: batikMen.Batik2Hijau, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: batikMen.Batik2Salem, color: "Salem" },
    ],
    price: 190000,
    rating: 5,
    gender: "Pria",
    sold: 200,
  },
  {
    id: 4,
    name: "Batik Mega Mendung",
    image: [
      { src: batikWomen.Batik4Merah, color: "Merah" },
      { src: batikWomen.Batik4Biru, color: "Biru" },
      { src: batikWomen.Batik4Hijau, color: "Hijau" },
      { src: batikWomen.Batik4Kuning, color: "Kuning" },
      // { src: batikWomen.Batik4Biru, color: "Jingga" },
      { src: batikWomen.Batik4Salem, color: "Salem" },
    ],
    price: 200000,
    rating: 4.8,
    gender: "Wanita",
    sold: 95,
  },
  {
    id: 5,
    name: "Batik Kawung",
    image: [
      { src: batikMen.Batik5Merah, color: "Merah" },
      { src: batikMen.Batik5Biru, color: "Biru" },
      { src: batikMen.Batik5Hijau, color: "Hijau" },
    ],
    price: 240000,
    rating: 4.3,
    gender: "Pria",
    sold: 75,
  },
  {
    id: 6,
    name: "Batik Parang",
    image: [
      { src: Batik3, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 180000,
    rating: 4.7,
    gender: "Pria",
    sold: 150,
  },
  {
    id: 7,
    name: "Batik Sekar Jagad",
    image: [
      { src: Batik1, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 230000,
    rating: 5,
    gender: "Pria",
    sold: 110,
  },
  {
    id: 8,
    name: "Batik Lasem",
    image: [
      { src: Batik2, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 170000,
    rating: 3.8,
    gender: "Pria",
    sold: 60,
  },
  {
    id: 9,
    name: "Batik Cirebon",
    image: [
      { src: Batik4, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 200000,
    rating: 4.6,
    gender: "Unisex",
    sold: 180,
  },
  {
    id: 10,
    name: "Batik Solo",
    image: [
      { src: Batik3, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 150000,
    rating: 4.5,
    gender: "Pria",
    sold: 130,
  },
  {
    id: 11,
    name: "Batik Yogyakarta",
    image: [
      { src: Batik2, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 250000,
    rating: 4.9,
    gender: "Pria",
    sold: 140,
  },
  {
    id: 12,
    name: "Batik Bali",
    image: [
      { src: Batik1, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 140000,
    rating: 4.4,
    gender: "Pria",
    sold: 100,
  },
  {
    id: 13,
    name: "Batik Banten",
    image: [
      { src: Batik3, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 210000,
    rating: 4.7,
    gender: "Pria",
    sold: 90,
  },
  {
    id: 14,
    name: "Batik Malang",
    image: [
      { src: Batik2, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 150000,
    rating: 4.2,
    gender: "Unisex",
    sold: 50,
  },
  {
    id: 15,
    name: "Batik Dayak",
    image: [
      { src: Batik3, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 240000,
    rating: 4.8,
    gender: "Unisex",
    sold: 120,
  },
  {
    id: 16,
    name: "Batik Betawi",
    image: [
      { src: Batik1, color: "Merah" },
      { src: Batik2, color: "Biru" },
      { src: Batik3, color: "Hijau" },
      { src: batikMen.Batik2Kuning, color: "Kuning" },
      { src: Batik1, color: "Jingga" },
      { src: Batik2, color: "Salem" },
    ],
    price: 220000,
    rating: 4.8,
    gender: "Unisex",
    sold: 120,
  },
];
